### ISSUE TITLE
Can't set default profile

### ISSUE THREAD

**Issue by MoustafaAMahmoud** [MacHu-GWU/afwf_s3-project#2]
I got the below error while trying to setup the aws-cli-set-profile

```
Traceback (most recent call last):
  File "/Users/mostafa/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9B319729-6E31-4414-86F4-976474E069B5/lib/afwf/workflow.py", line 139, in run
    self._run(arg=arg, debug=debug)
  File "/Users/mostafa/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9B319729-6E31-4414-86F4-976474E069B5/lib/afwf/workflow.py", line 117, in _run
    sf = handler.handler(query)
  File "/Users/mostafa/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9B319729-6E31-4414-86F4-976474E069B5/lib/afwf/handler.py", line 84, in handler
    return self.main(**self.parse_query(query))
  File "/Users/mostafa/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9B319729-6E31-4414-86F4-976474E069B5/lib/afwf_awscli_profile/handlers/view_or_edit_settings.py", line 17, in main
    settings = Settings.read()
  File "/Users/mostafa/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.9B319729-6E31-4414-86F4-976474E069B5/lib/afwf_awscli_profile/settings.py", line 21, in read
    return Settings(**json.loads(path.read_text()))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 20 (char 21)


```
![image](https://user-images.githubusercontent.com/13502087/232179078-cdefaaea-7cd5-4296-9f7f-582fddfea671.png)

**Comment by MoustafaAMahmoud** [comment]
Fixed, it was an issue in the path
